name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: chmod +x *.sh ; ./install.sh ; x86_64-w64-mingw32-gcc -c COFFLoader3.c -o COFFLoader.o -D_CRT_SECURE_NO_WARNINGS
    - name: make
      run: make windows

